"use strict";
let msg = "hello";
console.log(msg);
//@ts-ignore
let firstname = "raj";
let lastname = "shingade";
let fullname = firstname.concat(lastname);
console.log(fullname);
let sentence = "hello brother raj this side";
let sentencelength = sentence.length;
console.log(sentencelength);
let text = "Hello I am here to do the task and doing the next also";
let uppercaseText = text.toUpperCase();
let lowercaseText = uppercaseText.toLowerCase();
console.log(uppercaseText);
console.log(lowercaseText);
let longtext = "hello I am raj shingade";
let shortText = longtext.slice(0, 10);
let substring = longtext.substring(0, 10);
console.log(shortText);
console.log(substring);
let str1 = "hello brother";
let str2 = "hello sister";
let result = str1 == str2;
console.log(result);
let product = "acer laptop";
let price = 10000;
let productdetails = `the product name is ${product} and the price is ${price}`;
console.log(productdetails);
